### ISSUE TITLE
Compatibility with Matomo 3.13.0 ?

### ISSUE THREAD

**Issue by Himra** [Zeichen32/PiwikCustomOptOut#61]
Seems like the plugin doesn't work with this version.
Re-installation does not fix the problem.

I need this useful plugin because I want to use my own font.

Does anyone run it with this version?

**Comment by Himra** [comment]
this is the content of the linked CSS file
The font is in the same directory as the CSS file
It always renders with Arial

```css
@font-face {
	font-family: 'orkneylight';
	src: url('orkney-light-webfont.woff') format('woff');
	font-weight: normal;
	font-style: normal;
}

body{
	background:transparent;
	margin: 0;
	font-family: 'orkneylight', Arial;
	font-size: 1.1rem;
}
```
